services:
  db:
    image: postgres
    container_name: enotes-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sif
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enotes_db
    networks:
      - enotes-spring
    volumes:
      - enotes-postgres:/var/lib/postgresql/data


networks:
  enotes-spring:
    driver: bridge
volumes:
  enotes-postgres:
    driver: local